[build-system]
requires = ["setuptools>=69.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "it-automation-toolkit"
version = "0.1.0"
description = "Enterprise IT Automation Framework built with Python."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"

authors = [
    { name = "José Daniel Portillo" }
]

keywords = [
    "automation",
    "it",
    "python",
    "devops",
    "system",
    "linux",
    "windows"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: System :: Systems Administration",
    "Topic :: System :: Monitoring",
    "Topic :: Security",
]

dependencies = [
    "psutil>=7.2.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "build>=1.0.0",
    "twine>=5.0.0",
]

[project.urls]
Homepage = "https://github.com/PortilloLab/it-automation-toolkit"
Documentation = "https://github.com/PortilloLab/it-automation-toolkit#readme"
Repository = "https://github.com/PortilloLab/it-automation-toolkit"
Issues = "https://github.com/PortilloLab/it-automation-toolkit/issues"
Changelog = "https://github.com/PortilloLab/it-automation-toolkit/releases"

[project.scripts]
itat = "itat.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
itat = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]